#!/usr/bin/env bash
sudo cp /etc/resolv.conf root64/etc/
sudo mount --bind /dev/ root64/dev
sudo chroot root64
mount -t proc none /proc && mount -t sysfs none /sys && mount -t devpts none /dev/pts
export HOME=/root && export LC_ALL=C
