#!/bin/bash
sudo rm ./dvd/casper/filesystem.squashfs 
sudo chmod +w ./dvd/casper/filesystem.manifest
sudo mksquashfs root64 ./dvd/casper/filesystem.squashfs
sudo su
sudo chroot ./root64 dpkg-query -W --showformat='${Package} ${Version}\n' > ./dvd/casper/filesystem.manifest
printf $(sudo du -sx --block-size=1 root64 | cut -f1) > ./dvd/casper/filesystem.size
exit
sudo cp ./dvd/casper/filesystem.manifest ./dvd/casper/filesystem.manifest-desktop
cd ./dvd/
find -type f -print0 | sudo xargs -0 md5sum | grep -v isolinux/boot.cat | sudo tee MD5SUMS
cd ..
sudo mkisofs -r -V "sugos-1.0-xfce-amd64" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../sugos-1.0-xfce-amd64-beta.iso dvd
cd .. && sudo chmod 777 sugos-1.0-xfce-amd64-beta.iso
isohybrid sugos-1.0-xfce-amd64-beta.iso
